apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsc-http-server
spec:
  selector:
    matchLabels:
      app: lsc-http-server
  template:
    metadata:
      labels:
        app: lsc-http-server
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: lsc-pvc